# Generated by Django 3.1.3 on 2021-06-09 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('path', models.CharField(blank=True, max_length=50, null=True, verbose_name='Caminho do menu')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='core.menuitems', verbose_name='Item pai')),
            ],
            options={
                'verbose_name': 'item de menu',
                'verbose_name_plural': 'itens de menu',
            },
        ),
    ]
