# Generated by Django 3.1.3 on 2021-06-10 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0003_menuitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'grupo de permissao de menu',
                'verbose_name_plural': 'grupos de permissões de menu',
            },
        ),
        migrations.CreateModel(
            name='MesaBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fichas', models.ManyToManyField(related_name='mesa', to='core.FichaBase', verbose_name='Personagens')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_core.mesabase_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='path',
            field=models.CharField(blank=True, help_text='Python/Django style', max_length=50, null=True, verbose_name='Caminho do menu'),
        ),
        migrations.DeleteModel(
            name='Mesa',
        ),
        migrations.AddField(
            model_name='menuperms',
            name='items_permited',
            field=models.ManyToManyField(blank=True, related_name='menu_perms', to='core.MenuItems', verbose_name='Itens liberados'),
        ),
    ]
