# Generated by Django 3.1.3 on 2021-06-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210610_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='permissions_groups', to='core.MenuPerms', verbose_name='Permissões'),
        ),
    ]
