# Generated by Django 3.1.3 on 2021-06-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210619_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesabase',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='Nome da mesa'),
            preserve_default=False,
        ),
    ]
