# Generated by Django 3.1.3 on 2021-06-21 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_mesabase_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesabase',
            name='mestre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='mesas_mestradas', to=settings.AUTH_USER_MODEL, verbose_name='Mestre'),
        ),
        migrations.AlterField(
            model_name='fichainmesa',
            name='ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas_jogadas', to='core.fichabase', verbose_name='Ficha'),
        ),
    ]
