# Generated by Django 3.1.3 on 2021-09-04 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210621_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichabase',
            name='in_session',
            field=models.BooleanField(default=False, verbose_name='Está online na sessão'),
        ),
        migrations.AddField(
            model_name='fichabase',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='fichas_mesa', to='core.mesabase', verbose_name='Mesa'),
        ),
        migrations.DeleteModel(
            name='FichaInMesa',
        ),
    ]
