# Generated by Django 3.1.3 on 2021-09-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210904_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sobrenome'),
        ),
    ]
