# Generated by Django 3.1.3 on 2021-10-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210911_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Nickname'),
        ),
    ]
