# Generated by Django 3.1.3 on 2020-11-03 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('fichabase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.fichabase')),
                ('xp', models.IntegerField(default=0, verbose_name='XP')),
            ],
            options={
                'verbose_name': 'ficha(dnd)',
                'verbose_name_plural': 'fichas(dnd)',
            },
            bases=('core.fichabase',),
        ),
    ]
