# Generated by Django 3.1.3 on 2020-11-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ficha',
            options={'verbose_name': 'ficha', 'verbose_name_plural': 'fichas'},
        ),
        migrations.AddField(
            model_name='ficha',
            name='user_kind',
            field=models.IntegerField(choices=[(0, 'Leal e bom'), (1, 'Leal e neutro'), (2, 'Leal e mau'), (3, 'Neutro e bom'), (4, 'Neutro e neutro'), (5, 'Neutro e mau'), (6, 'Caótico e bom'), (7, 'Caótico e neutro'), (8, 'Caótico e mau')], default=4, verbose_name='Alinhamento'),
            preserve_default=False,
        ),
    ]
