# Generated by Django 3.1.3 on 2020-11-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0002_auto_20201103_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficha',
            old_name='user_kind',
            new_name='alignment',
        ),
        migrations.AddField(
            model_name='ficha',
            name='charisma',
            field=models.IntegerField(default=1, verbose_name='Carisma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha',
            name='constitution',
            field=models.IntegerField(default=1, verbose_name='Constituição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha',
            name='dexterity',
            field=models.IntegerField(default=1, verbose_name='Destreza'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha',
            name='inteligence',
            field=models.IntegerField(default=1, verbose_name='Inteligência'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha',
            name='strenght',
            field=models.IntegerField(default=1, verbose_name='Força'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha',
            name='wisdom',
            field=models.IntegerField(default=1, verbose_name='Sabedoria'),
            preserve_default=False,
        ),
    ]
