# Generated by Django 3.1.3 on 2020-11-03 10:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('dnd', '0004_auto_20201103_1016'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ficha',
            new_name='FichaDND',
        ),
    ]
