# Generated by Django 3.1.3 on 2020-11-03 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0005_auto_20201103_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='RacesDND',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_name', models.CharField(max_length=50, verbose_name='Nome')),
                ('str_inc', models.IntegerField(default=0, verbose_name='Incremento de força')),
                ('dex_inc', models.IntegerField(default=0, verbose_name='Incremento de destreza')),
                ('con_inc', models.IntegerField(default=0, verbose_name='Incremento de constituição')),
                ('int_inc', models.IntegerField(default=0, verbose_name='Incremento de inteligência')),
                ('wis_inc', models.IntegerField(default=0, verbose_name='Incremento de sabedoria')),
                ('cha_inc', models.IntegerField(default=0, verbose_name='Incremento de carisma')),
                ('mov_speed', models.FloatField(default=0, verbose_name='Deslocamento')),
            ],
        ),
    ]
