# Generated by Django 3.1.3 on 2020-11-03 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0006_auto_20201103_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='racesdnd',
            options={'verbose_name': 'raça', 'verbose_name_plural': 'raças'},
        ),
        migrations.AddField(
            model_name='fichadnd',
            name='race',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='raca', to='dnd.racesdnd'),
            preserve_default=False,
        ),
    ]
