# Generated by Django 3.1.3 on 2020-11-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0007_auto_20201103_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesdnd',
            name='race_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
