# Generated by Django 3.1.3 on 2020-11-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0008_racesdnd_race_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesdnd',
            name='homebrew',
            field=models.BooleanField(default=True, verbose_name='Homebrew'),
        ),
    ]
