# Generated by Django 3.1.3 on 2020-11-05 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0009_racesdnd_homebrew'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguagesDND',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'idioma',
                'verbose_name_plural': 'idiomas',
            },
        ),
        migrations.CreateModel(
            name='RaceTraitsDND',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'traço racial',
                'verbose_name_plural': 'traços raciais',
            },
        ),
        migrations.AddField(
            model_name='racesdnd',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='racesdnd',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='racesdnd',
            name='languages',
            field=models.ManyToManyField(related_name='idiomas', to='dnd.LanguagesDND'),
        ),
        migrations.AddField(
            model_name='racesdnd',
            name='traits',
            field=models.ManyToManyField(related_name='tracos', to='dnd.RaceTraitsDND'),
        ),
    ]
