# Generated by Django 3.1.3 on 2020-11-09 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0010_auto_20201105_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasseDND',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'classe',
                'verbose_name_plural': 'classes',
            },
        ),
        migrations.AlterField(
            model_name='racesdnd',
            name='languages',
            field=models.ManyToManyField(related_name='idiomas', to='dnd.LanguagesDND', verbose_name='Idiomas'),
        ),
        migrations.AlterField(
            model_name='racesdnd',
            name='traits',
            field=models.ManyToManyField(related_name='tracos', to='dnd.RaceTraitsDND', verbose_name='Traços'),
        ),
        migrations.CreateModel(
            name='ClassesFichaDND',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.IntegerField(default=1, verbose_name='Nível da classe')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to='dnd.classednd')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='dnd.fichadnd')),
            ],
            options={
                'verbose_name': 'classe em ficha',
                'verbose_name_plural': 'classes em fichas',
            },
        ),
    ]
