# Generated by Django 3.1.3 on 2020-11-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0011_auto_20201109_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='classednd',
            name='saving_cha',
            field=models.BooleanField(default=False, verbose_name='Proficiência em resistência de carisma'),
        ),
        migrations.AddField(
            model_name='classednd',
            name='saving_con',
            field=models.BooleanField(default=False, verbose_name='Proficiência em resistência de constituição'),
        ),
        migrations.AddField(
            model_name='classednd',
            name='saving_dex',
            field=models.BooleanField(default=False, verbose_name='Proficiência em resistência de destreza'),
        ),
        migrations.AddField(
            model_name='classednd',
            name='saving_int',
            field=models.BooleanField(default=False, verbose_name='Proficiência em resistência de inteligência'),
        ),
        migrations.AddField(
            model_name='classednd',
            name='saving_str',
            field=models.BooleanField(default=False, verbose_name='Proficiência em resistência de força'),
        ),
        migrations.AddField(
            model_name='classednd',
            name='saving_wis',
            field=models.BooleanField(default=False, verbose_name='Proficiência em resistência de sabedoria'),
        ),
    ]
