# Generated by Django 3.1.3 on 2020-11-10 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0013_classednd_prequesitie_races'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadnd',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raca', to='dnd.racesdnd', verbose_name='Raça'),
        ),
        migrations.CreateModel(
            name='SkillChoiceRaceDND',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.IntegerField(choices=[], verbose_name='Perícia')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='dnd.racesdnd')),
            ],
            options={
                'verbose_name': 'skill por raça',
                'verbose_name_plural': 'skills por raça',
            },
        ),
    ]
