# Generated by Django 3.1.3 on 2020-11-10 13:00

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0014_auto_20201110_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesdnd',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Acrobacia'), (1, 'Adestrar animais'), (2, 'Arcanismo'), (3, 'Atletismo'), (4, 'Atuação'), (5, 'Enganação')], default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SkillChoiceRaceDND',
        ),
    ]
