# Generated by Django 3.1.3 on 2020-11-10 13:19

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0015_auto_20201110_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesdnd',
            name='skill_choice_limit',
            field=models.IntegerField(blank=True, help_text='se 0 ou vazio, não existe limite, pega todas as perícias', null=True, verbose_name='Limite de escolha de perícias na ficha'),
        ),
        migrations.AlterField(
            model_name='racesdnd',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Acrobacia'), (1, 'Adestrar animais'), (2, 'Arcanismo'), (3, 'Atletismo'), (4, 'Atuação'), (5, 'Enganação'), (6, 'Furtividade'), (7, 'História'), (8, 'Intimidação'), (9, 'Intuição'), (10, 'Investigação'), (11, 'Medicina'), (12, 'Natureza'), (13, 'Percepção'), (14, 'Persuasão'), (15, 'Prestidigitação'), (16, 'Religião'), (17, 'Sobrevivência')], max_length=43, null=True, verbose_name='Proficiência em perícias'),
        ),
    ]
