# Generated by Django 3.1.3 on 2020-11-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0016_auto_20201110_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedentesDND',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='classednd',
            old_name='prequesitie_races',
            new_name='prequesite_races',
        ),
        migrations.AlterField(
            model_name='racesdnd',
            name='skill_choice_limit',
            field=models.IntegerField(blank=True, help_text='se 0 ou vazio, não existe limite, pega todas as perícias selecionadas', null=True, verbose_name='Limite de escolha de perícias na ficha'),
        ),
    ]
