# Generated by Django 3.1.3 on 2020-11-18 09:58

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0019_classesfichadnd_selected_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadnd',
            name='race_skill_selected',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Acrobacia'), (1, 'Adestrar animais'), (2, 'Arcanismo'), (3, 'Atletismo'), (4, 'Atuação'), (5, 'Enganação'), (6, 'Furtividade'), (7, 'História'), (8, 'Intimidação'), (9, 'Intuição'), (10, 'Investigação'), (11, 'Medicina'), (12, 'Natureza'), (13, 'Percepção'), (14, 'Persuasão'), (15, 'Prestidigitação'), (16, 'Religião'), (17, 'Sobrevivência')], max_length=43, null=True, verbose_name='Proficiência em perícias da raça'),
        ),
    ]
