# Generated by Django 3.1.3 on 2020-12-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0020_fichadnd_race_skill_selected'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrapsDND',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('kind', models.CharField(max_length=200, verbose_name='Tipo')),
                ('level', models.IntegerField(choices=[(0, '1-4'), (1, '5-8'), (2, '9-12'), (3, '13-16'), (4, '17-20')], verbose_name='Nível')),
                ('danger', models.IntegerField(choices=[(0, 'Setback'), (1, 'Moderado'), (2, 'Perigoso'), (3, 'Muito perigoso'), (4, 'Mortal')], verbose_name='Nível de perigo')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('trigger_kind', models.CharField(max_length=200, verbose_name='Tipo de gatilho')),
                ('trigger_description', models.TextField(verbose_name='Descrição do gatilho')),
                ('effect_kind', models.CharField(max_length=200, verbose_name='Tipo de efeito')),
                ('effect_description', models.TextField(verbose_name='Descrição do efeito')),
                ('countermeasures', models.TextField(verbose_name='Contramedidas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='classednd',
            name='prequesite_races',
            field=models.ManyToManyField(blank=True, related_name='racas_prereq', to='dnd.RacesDND', verbose_name='Prerequisitos de raça'),
        ),
    ]
