# Generated by Django 3.1.3 on 2021-04-26 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0021_auto_20201210_0836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trapsdnd',
            options={'verbose_name': 'armadilha', 'verbose_name_plural': 'armadilhas'},
        ),
    ]
