"""
Django settings for rpg_tracker project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'developmentKey')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # third-party
    'polymorphic',
    'widget_tweaks',
    'multiselectfield',
    'mathfilters',
    'django_tables2',
    'rest_framework',
    'channels',
    'social_django',
    'rest_framework_simplejwt',
    'rest_social_auth', 
    'corsheaders',
    'hbcommons',
    # rpg
    'rpg_tracker.core',
    'rpg_tracker.accounts',
    'rpg_tracker.dnd',
    'rpg_tracker.coc',
    'rpg_tracker.hp',
    'rpg_tracker.feature_toggle',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rpg_tracker.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

ASGI_APPLICATION = 'rpg_tracker.asgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/core/static/'

# Auth
AUTH_USER_MODEL = 'core.Usuario'
LOGIN_URL = 'core:login'
LOGIN_REDIRECT_URL = 'core:home'
LOGOUT_URL = 'core:logout'
LOGOUT_REDIRECT_URL = 'core:login'
AUTHENTICATION_BACKENDS = [
    'hbcommons.oauthconsumer.HannaBanannaOAuth2',
    'social_core.backends.discord.DiscordOAuth2',
    'django.contrib.auth.backends.ModelBackend',
]

# REST
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
}

# CORS
CORS_ORIGIN_WHITELIST = [
    'http://localhost:3000',
    'http://localhost:8080',
]

# Channels
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [os.getenv('REDIS_URL', 'redis://localhost:6379')],
        },
    },
}

# Tables
DJANGO_TABLES2_TEMPLATE = "django_tables2/bootstrap4.html"

# Social Auth
REST_SOCIAL_OAUTH_REDIRECT_URI = "/login/oauth/callback"
SOCIAL_AUTH_DISCORD_KEY = '855087409417814038'
SOCIAL_AUTH_DISCORD_SECRET = os.getenv('DISCORD_OAUTH_SECRET', 'discordSecret') 
SOCIAL_AUTH_DISCORD_SCOPE = ['email']
SOCIAL_AUTH_HANNABANANNA_KEY = os.getenv("HBAUTH_KEY","fumNnHbpqr6Ya4UuPhXbDeBKVpCZXLgclHTbqkD6")
SOCIAL_AUTH_HANNABANANNA_SECRET = os.getenv("HBAUTH_SECRET", "tKHFVtcUl0Kc1ja3oUTmyowDOFhLEmVhB2eAvlOTmBD7NnqvZ4ixROwQHvjZGcEDqjGNLCQFrmIiA822GCdx3G50DzB4GgAjD3ALrmUK1rw61azrsSdMvvBz1olmroVw")

HANNABANANNA_AUTH_URL = os.getenv("HBAUTH_URL", "http://localhost:8000")

#  Sentry
sentry_sdk.init(
    dsn=os.getenv('SENTRY_DSN', ""),
    integrations=[DjangoIntegration()]
)

# DEPLOY TO HEROKU
if not DEBUG:
    # import dj_database_url
    import django_heroku
    django_heroku.settings(locals())
    # Force https redirect
    SECURE_SSL_REDIRECT = True
    # Honor the 'X-Forwarded-Proto' header for request.is_secure()
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # Force HTTPS in the final URIs
    SOCIAL_AUTH_REDIRECT_IS_HTTPS = True
    CORS_ORIGIN_WHITELIST = [
        'http://rpgtracker.herokuapp.com',
        'https://rpgtracker.herokuapp.com',
    ]