# Generated by Django 3.1.3 on 2021-08-12 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hp', '0002_auto_20210808_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('material_escolar', models.BooleanField(default=False, verbose_name='É material escolar')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EquipamentoFicha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equip', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fichas', to='hp.equipamentos', verbose_name='Equipamentos')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='hp.fichahp', verbose_name='Ficha')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
