# Generated by Django 3.1.3 on 2021-09-04 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hp', '0004_cartafoliouniversitas_categoriafoliouniversitas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipamentoficha',
            options={'verbose_name': 'equipamento em ficha', 'verbose_name_plural': 'equipamentos em fichas'},
        ),
        migrations.AlterModelOptions(
            name='equipamentos',
            options={'verbose_name': 'equipamento', 'verbose_name_plural': 'equipamentos'},
        ),
        migrations.AlterModelOptions(
            name='periciasespecializacoes',
            options={'verbose_name': 'perícia e especialização', 'verbose_name_plural': 'perícias e especializações'},
        ),
        migrations.CreateModel(
            name='CartaFolioUniversitasUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ficha_found', to='hp.cartafoliouniversitas', verbose_name='Carta')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cartas', to='hp.fichahp', verbose_name='Ficha')),
            ],
            options={
                'verbose_name': 'carta do folio universitas encontrada por ficha',
                'verbose_name_plural': 'cartas do folio universitas encontradas por fichas',
            },
        ),
    ]
