# Generated by Django 3.1.3 on 2020-11-03 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaCOC',
            fields=[
                ('fichabase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.fichabase')),
                ('age', models.IntegerField(verbose_name='Idade')),
                ('sex', models.CharField(max_length=50, verbose_name='Sexo')),
                ('birthplace', models.CharField(max_length=50, verbose_name='Local de nascimento')),
                ('residence', models.CharField(max_length=50, verbose_name='Residência')),
            ],
            options={
                'verbose_name': 'ficha',
                'verbose_name_plural': 'fichas',
            },
            bases=('core.fichabase',),
        ),
    ]
