# Generated by Django 3.1.3 on 2021-04-26 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichacoc',
            name='appearence',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Aparência'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichacoc',
            name='constitution',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Constituição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichacoc',
            name='dexterity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Destreza'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichacoc',
            name='education',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Educação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichacoc',
            name='hp',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='HP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichacoc',
            name='inteligence',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Inteligência'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichacoc',
            name='luck',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Sorte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichacoc',
            name='max_hp',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='HP Máximo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichacoc',
            name='max_mp',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='MP Máximo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichacoc',
            name='max_san',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Sanidade Máxima'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichacoc',
            name='move_rate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Movimento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichacoc',
            name='mp',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='MP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichacoc',
            name='power',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Poder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichacoc',
            name='san',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Sanidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichacoc',
            name='size',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tamanho'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichacoc',
            name='start_san',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Sanidade Inicial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichacoc',
            name='strength',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Força'),
            preserve_default=False,
        ),
    ]
