# Generated by Django 3.1.3 on 2021-04-30 22:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coc', '0002_auto_20210426_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichacoc',
            name='bonus_dmg',
            field=models.IntegerField(default=0, verbose_name='Bonus de dano'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichacoc',
            name='build',
            field=models.IntegerField(default=0, verbose_name='Corpo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichacoc',
            name='dodge',
            field=models.IntegerField(default=0, verbose_name='Esquiva'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fichacoc',
            name='max_san',
            field=models.IntegerField(default=99, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Sanidade Máxima'),
        ),
    ]
