# Generated by Django 3.1.3 on 2021-04-30 22:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coc', '0003_auto_20210430_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichacoc',
            name='bonus_dmg',
            field=models.IntegerField(blank=True, verbose_name='Bonus de dano'),
        ),
        migrations.AlterField(
            model_name='fichacoc',
            name='build',
            field=models.IntegerField(blank=True, verbose_name='Corpo'),
        ),
        migrations.AlterField(
            model_name='fichacoc',
            name='dodge',
            field=models.IntegerField(blank=True, verbose_name='Esquiva'),
        ),
        migrations.AlterField(
            model_name='fichacoc',
            name='hp',
            field=models.IntegerField(blank=True, verbose_name='HP'),
        ),
        migrations.AlterField(
            model_name='fichacoc',
            name='max_hp',
            field=models.IntegerField(blank=True, verbose_name='HP Máximo'),
        ),
        migrations.AlterField(
            model_name='fichacoc',
            name='max_mp',
            field=models.IntegerField(blank=True, verbose_name='MP Máximo'),
        ),
        migrations.AlterField(
            model_name='fichacoc',
            name='max_san',
            field=models.IntegerField(blank=True, default=99, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Sanidade Máxima'),
        ),
        migrations.AlterField(
            model_name='fichacoc',
            name='move_rate',
            field=models.IntegerField(blank=True, verbose_name='Movimento'),
        ),
        migrations.AlterField(
            model_name='fichacoc',
            name='mp',
            field=models.IntegerField(blank=True, verbose_name='MP'),
        ),
        migrations.AlterField(
            model_name='fichacoc',
            name='san',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Sanidade'),
        ),
        migrations.AlterField(
            model_name='fichacoc',
            name='start_san',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Sanidade Inicial'),
        ),
    ]
