# Generated by Django 3.1.3 on 2021-05-25 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coc', '0004_auto_20210430_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('skill_points_calc_rule', models.IntegerField(choices=[(0, 'EDU x 4'), (1, 'EDU x 2 + INT x 2'), (2, 'EDU x 2 + APP x 2'), (3, 'EDU x 2 + STR x 2'), (4, 'EDU x 2 + DEX x 2'), (5, 'EDU x 2 + (STR x 2 ou DEX x 2)'), (6, 'EDU x 2 + (APP x 2 ou DEX x 2)'), (7, 'EDU x 2 + (STR x 2 ou DEX x 2 ou APP x 2)')], default=0, verbose_name='Regra de cálculo para Pontos de Ocupação')),
            ],
            options={
                'verbose_name': 'ocupação',
                'verbose_name_plural': 'ocupações',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'perícia',
                'verbose_name_plural': 'perícias',
            },
        ),
        migrations.CreateModel(
            name='Weapons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'arma',
                'verbose_name_plural': 'armas',
            },
        ),
        migrations.AddField(
            model_name='fichacoc',
            name='ocupational_skill_points',
            field=models.IntegerField(blank=True, default=1, verbose_name='Pontos de perícia ocupacionais'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichacoc',
            name='personal_interest_skill_points',
            field=models.IntegerField(blank=True, default=1, verbose_name='Pontos de perícia de interese pessoais'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichacoc',
            name='ocupation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='fichas', to='coc.ocupation', verbose_name='Ocupação'),
            preserve_default=False,
        ),
    ]
