# Generated by Django 3.1.3 on 2021-05-26 19:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coc', '0005_auto_20210525_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocupation',
            name='credit_rating_max',
            field=models.IntegerField(default=1, verbose_name='Rank de Crédito Máximo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ocupation',
            name='credit_rating_min',
            field=models.IntegerField(default=1, verbose_name='Rank de Crédito Mínimo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ocupation',
            name='skills',
            field=models.ManyToManyField(related_name='ocupations', to='coc.Skills', verbose_name='Perícias disponiveis'),
        ),
        migrations.AddField(
            model_name='ocupation',
            name='sugested_contacts',
            field=models.TextField(blank=True, null=True, verbose_name='Contatos sugeridos'),
        ),
        migrations.AddField(
            model_name='skills',
            name='base_value',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Valor base'),
        ),
        migrations.AddField(
            model_name='skills',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skills',
            name='parent_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='coc.skills', verbose_name='Skill pai'),
        ),
        migrations.AddField(
            model_name='skills',
            name='skill_kind',
            field=models.IntegerField(choices=[(0, 'Interpessoal'), (1, 'Investigação'), (2, 'Combate')], default=1, verbose_name='Tipo de skill'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skills',
            name='skill_rarity',
            field=models.IntegerField(choices=[(0, 'Comum'), (1, '1920 Era'), (2, 'Moderna')], default=1, verbose_name='Raridade'),
            preserve_default=False,
        ),
    ]
