# Generated by Django 3.1.3 on 2021-05-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coc', '0006_auto_20210526_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocupation',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, related_name='ocupations', to='coc.Skills', verbose_name='Perícias disponiveis'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill_kind',
            field=models.IntegerField(choices=[(0, 'Interpessoal'), (1, 'Investigação'), (2, 'Combate'), (3, 'Comum')], verbose_name='Tipo de skill'),
        ),
    ]
