# Generated by Django 3.1.3 on 2021-05-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coc', '0007_auto_20210526_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocupation',
            name='skill_choice_2_kind',
            field=models.IntegerField(blank=True, choices=[(0, 'Interpessoal'), (1, 'Investigação'), (2, 'Combate'), (3, 'Comum')], null=True, verbose_name='Tipo da skill'),
        ),
        migrations.AddField(
            model_name='ocupation',
            name='skill_choices',
            field=models.IntegerField(blank=True, null=True, verbose_name='Qtde de skills como especialidades pessoais ou de época'),
        ),
        migrations.AddField(
            model_name='ocupation',
            name='skill_choices_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Qtde de skills do tipo'),
        ),
    ]
