# Generated by Django 3.1.3 on 2021-05-27 08:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coc', '0008_auto_20210526_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichacoc',
            name='ocupation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fichas', to='coc.ocupation', verbose_name='Ocupação'),
        ),
        migrations.CreateModel(
            name='SkillsOnFicha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Valor')),
                ('skill_improv', models.BooleanField(default=False, verbose_name='Improvement')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='skills', to='coc.fichacoc', verbose_name='Ficha')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fichas', to='coc.skills', verbose_name='Skill')),
            ],
            options={
                'verbose_name': 'perícia em ficha',
                'verbose_name_plural': 'perícias em fichas',
            },
        ),
    ]
