# Generated by Django 3.1.3 on 2021-05-27 12:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coc', '0009_auto_20210527_0800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ammo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('rounds_shot_with_each', models.IntegerField(default=1, verbose_name='Tiros com cada munição')),
            ],
            options={
                'verbose_name': 'munição',
                'verbose_name_plural': 'munições',
            },
        ),
        migrations.AddField(
            model_name='weapons',
            name='ammo_left',
            field=models.IntegerField(blank=True, null=True, verbose_name='Munição disponível'),
        ),
        migrations.AddField(
            model_name='weapons',
            name='attacks',
            field=models.IntegerField(default=1, verbose_name='Ataques por round'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapons',
            name='damage',
            field=models.CharField(default=1, max_length=20, verbose_name='Dano'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapons',
            name='is_melee',
            field=models.BooleanField(default=True, verbose_name='Mano a mano'),
        ),
        migrations.AddField(
            model_name='weapons',
            name='malfunction',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Falha'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapons',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapons',
            name='range',
            field=models.IntegerField(blank=True, null=True, verbose_name='Alcance'),
        ),
        migrations.AddField(
            model_name='weapons',
            name='rounds_left',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tiros restantes'),
        ),
        migrations.AddField(
            model_name='weapons',
            name='ammo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='guns', to='coc.ammo', verbose_name='Munição'),
        ),
    ]
