# Generated by Django 3.1.3 on 2021-05-27 13:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coc', '0010_auto_20210527_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapons',
            name='ammo_left',
        ),
        migrations.AlterField(
            model_name='weapons',
            name='malfunction',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Falha'),
        ),
        migrations.CreateModel(
            name='WeaponsInFicha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ammo_left', models.IntegerField(blank=True, null=True, verbose_name='Munição disponível')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coc.fichacoc', verbose_name='Ficha')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fichas', to='coc.weapons', verbose_name='Arma')),
            ],
            options={
                'verbose_name': 'arma em ficha',
                'verbose_name_plural': 'armas em fichas',
            },
        ),
    ]
