# Generated by Django 3.1.3 on 2021-06-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coc', '0013_fichacoc_major_wound'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichacoc',
            name='indefinity_insanity',
            field=models.BooleanField(default=False, verbose_name='Insanidade Indefinida'),
        ),
        migrations.AddField(
            model_name='fichacoc',
            name='temporary_insanity',
            field=models.BooleanField(default=False, verbose_name='Insanidade Temporária'),
        ),
    ]
