# Generated by Django 3.1.3 on 2021-06-03 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coc', '0014_auto_20210601_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapons',
            name='skill_used',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='weapons', to='coc.skills', verbose_name='Skill usada'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weaponsinficha',
            name='ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapons', to='coc.fichacoc', verbose_name='Ficha'),
        ),
    ]
