# Generated by Django 3.1.3 on 2021-06-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coc', '0015_auto_20210603_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichacoc',
            name='credit_rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Renk de crédito'),
        ),
    ]
