# Generated by Django 3.1.3 on 2021-06-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coc', '0016_fichacoc_credit_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='weaponsinficha',
            name='qtde_weapons',
            field=models.IntegerField(default=1, verbose_name='Quantidade de armas'),
        ),
    ]
