# Generated by Django 3.1.3 on 2021-06-07 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coc', '0017_weaponsinficha_qtde_weapons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weaponsinficha',
            name='qtde_weapons',
        ),
    ]
