# Generated by Django 3.1.3 on 2021-06-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coc', '0018_remove_weaponsinficha_qtde_weapons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocupation',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='ocupations', to='coc.Skills', verbose_name='Perícias disponiveis'),
        ),
    ]
