# Generated by Django 3.1.3 on 2021-06-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coc', '0019_auto_20210610_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='weaponsinficha',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apelido'),
        ),
    ]
