# Generated by Django 3.1.3 on 2021-06-17 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coc', '0020_weaponsinficha_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichacoc',
            name='cthulhu_mythos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cthulhu Mythos'),
        ),
        migrations.AddField(
            model_name='fichacoc',
            name='dodge_improv',
            field=models.BooleanField(default=False, verbose_name='Improv. Check na esquiva'),
        ),
        migrations.AddField(
            model_name='fichacoc',
            name='language_own',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Idioma natural'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichacoc',
            name='language_own_improv',
            field=models.BooleanField(default=False, verbose_name='Improv. Check no idioma natural'),
        ),
    ]
