# Generated by Django 3.1.3 on 2021-06-19 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210619_2213'),
        ('coc', '0021_auto_20210617_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesaCOC',
            fields=[
                ('mesabase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.mesabase')),
            ],
            options={
                'verbose_name': 'mesa',
                'verbose_name_plural': 'mesas',
            },
            bases=('core.mesabase',),
        ),
    ]
