# Generated by Django 3.1.3 on 2021-08-08 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coc', '0022_mesacoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichacoc',
            name='language_own',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Idioma natural'),
        ),
    ]
