# Generated by Django 3.1.3 on 2022-01-28 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coc', '0025_auto_20220113_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichacoc',
            name='pulp_talents',
            field=models.ManyToManyField(blank=True, related_name='fichas', to='coc.PulpTalents', verbose_name='Talentos (PCoC)'),
        ),
        migrations.AlterField(
            model_name='skillsonficha',
            name='ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='coc.fichacoc', verbose_name='Ficha'),
        ),
    ]
