# Generated by Django 3.2.12 on 2022-02-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coc', '0026_auto_20220128_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichacoc',
            name='bonus_dmg',
            field=models.CharField(blank=True, max_length=10, verbose_name='Bonus de dano'),
        ),
        migrations.AlterField(
            model_name='weapons',
            name='range',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Alcance'),
        ),
    ]
